#!/usr/bin/env bash
set -euo pipefail

SEQUENCE_CACHE_DIR="${SEQUENCE_CACHE_DIR:-perch_sequence_cache_labeled_all_full}"
LABELS_PATH="${LABELS_PATH:-input/train_soundscapes_labels.csv}"
SAMPLE_SUBMISSION_PATH="${SAMPLE_SUBMISSION_PATH:-input/sample_submission.csv}"
FOLD_ASSIGNMENT_PATH="${FOLD_ASSIGNMENT_PATH:-outputs/birdclef2026_gm/20260505_195634_convnextv2_atto.fcmae_ft_in1k/soundscape_segments_with_folds.csv}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/perch_sequence_ssm_labeled_all_cnn195634folds_v1}"
N_FOLDS="${N_FOLDS:-3}"
LIMIT_FILES="${LIMIT_FILES:--1}"
D_MODEL="${D_MODEL:-192}"
D_STATE="${D_STATE:-16}"
N_SSM_LAYERS="${N_SSM_LAYERS:-2}"
DROPOUT="${DROPOUT:-0.25}"
N_SITES="${N_SITES:-20}"
META_DIM="${META_DIM:-16}"
USE_CROSS_ATTN="${USE_CROSS_ATTN:-1}"
CROSS_ATTN_HEADS="${CROSS_ATTN_HEADS:-4}"
MLP_MIN_POS="${MLP_MIN_POS:-4}"
EPOCHS="${EPOCHS:-260}"
BATCH_SIZE="${BATCH_SIZE:-16}"
LR="${LR:-0.0005}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.001}"
POS_WEIGHT_POWER="${POS_WEIGHT_POWER:-0.5}"
POS_WEIGHT_MAX="${POS_WEIGHT_MAX:-12.0}"
PROTOCLR_WEIGHT="${PROTOCLR_WEIGHT:-0.0}"
PROTOCLR_TEMPERATURE="${PROTOCLR_TEMPERATURE:-0.12}"
PROTOCLR_MIN_CLASSES="${PROTOCLR_MIN_CLASSES:-2}"
PROTOCLR_MIN_POS_PER_CLASS="${PROTOCLR_MIN_POS_PER_CLASS:-1}"
TEACHER_OOF_PATH="${TEACHER_OOF_PATH:-}"
TEACHER_KEY="${TEACHER_KEY:-best}"
TEACHER_LOSS_WEIGHT="${TEACHER_LOSS_WEIGHT:-0.0}"
INNER_VAL_FILES="${INNER_VAL_FILES:-8}"
PATIENCE="${PATIENCE:-40}"
NUM_WORKERS="${NUM_WORKERS:-0}"
DEVICE="${DEVICE:-auto}"
SEED="${SEED:-2026}"

ARGS=(
  --sequence-cache-dir "${SEQUENCE_CACHE_DIR}"
  --labels-path "${LABELS_PATH}"
  --sample-submission-path "${SAMPLE_SUBMISSION_PATH}"
  --fold-assignment-path "${FOLD_ASSIGNMENT_PATH}"
  --output-dir "${OUTPUT_DIR}"
  --n-folds "${N_FOLDS}"
  --limit-files "${LIMIT_FILES}"
  --d-model "${D_MODEL}"
  --d-state "${D_STATE}"
  --n-ssm-layers "${N_SSM_LAYERS}"
  --dropout "${DROPOUT}"
  --n-sites "${N_SITES}"
  --meta-dim "${META_DIM}"
  --cross-attn-heads "${CROSS_ATTN_HEADS}"
  --mlp-min-pos "${MLP_MIN_POS}"
  --epochs "${EPOCHS}"
  --batch-size "${BATCH_SIZE}"
  --lr "${LR}"
  --weight-decay "${WEIGHT_DECAY}"
  --pos-weight-power "${POS_WEIGHT_POWER}"
  --pos-weight-max "${POS_WEIGHT_MAX}"
  --protoclr-weight "${PROTOCLR_WEIGHT}"
  --protoclr-temperature "${PROTOCLR_TEMPERATURE}"
  --protoclr-min-classes "${PROTOCLR_MIN_CLASSES}"
  --protoclr-min-pos-per-class "${PROTOCLR_MIN_POS_PER_CLASS}"
  --teacher-oof-path "${TEACHER_OOF_PATH}"
  --teacher-key "${TEACHER_KEY}"
  --teacher-loss-weight "${TEACHER_LOSS_WEIGHT}"
  --inner-val-files "${INNER_VAL_FILES}"
  --patience "${PATIENCE}"
  --num-workers "${NUM_WORKERS}"
  --device "${DEVICE}"
  --seed "${SEED}"
)

if [[ "${USE_CROSS_ATTN}" == "1" ]]; then
  ARGS+=(--use-cross-attn)
fi

/home/hjs/anaconda3/envs/transformers/bin/python birdclef2026_perch_sequence_ssm_train.py "${ARGS[@]}"
