#!/usr/bin/env bash
set -euo pipefail

PYTHON_BIN="${PYTHON_BIN:-/home/hjs/anaconda3/envs/transformers/bin/python}"
BASE_CACHE_DIR="${BASE_CACHE_DIR:-perch_cache_labeled_all}"
AUDIO_CACHE_DIR="${AUDIO_CACHE_DIR:-}"
LABELS_PATH="${LABELS_PATH:-input/train_soundscapes_labels.csv}"
SAMPLE_SUBMISSION_PATH="${SAMPLE_SUBMISSION_PATH:-input/sample_submission.csv}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/perch_embedding_mlp_labeled_cnn195634folds_v1}"
N_FOLDS="${N_FOLDS:-3}"
FOLD_ASSIGNMENT_PATH="${FOLD_ASSIGNMENT_PATH:-outputs/birdclef2026_gm/20260505_195634_convnextv2_atto.fcmae_ft_in1k/soundscape_segments_with_folds.csv}"
LIMIT_FILES="${LIMIT_FILES:--1}"
USE_AUDIO_PRETRAIN="${USE_AUDIO_PRETRAIN:-0}"
MLP_MIN_POS="${MLP_MIN_POS:-4}"
HIDDEN_DIMS="${HIDDEN_DIMS:-768,384}"
DROPOUT="${DROPOUT:-0.35}"
PROTOCLR_WEIGHT_STAGE1="${PROTOCLR_WEIGHT_STAGE1:-0.0}"
PROTOCLR_WEIGHT_STAGE2="${PROTOCLR_WEIGHT_STAGE2:-0.0}"
PROTOCLR_TEMPERATURE="${PROTOCLR_TEMPERATURE:-0.12}"
PROTOCLR_MIN_CLASSES="${PROTOCLR_MIN_CLASSES:-2}"
PROTOCLR_MIN_POS_PER_CLASS="${PROTOCLR_MIN_POS_PER_CLASS:-1}"
STAGE1_EPOCHS="${STAGE1_EPOCHS:-15}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-220}"
BATCH_SIZE="${BATCH_SIZE:-128}"
LR_STAGE1="${LR_STAGE1:-5e-4}"
LR_STAGE2="${LR_STAGE2:-3e-4}"
WEIGHT_DECAY="${WEIGHT_DECAY:-1e-3}"
POS_WEIGHT_POWER="${POS_WEIGHT_POWER:-0.5}"
POS_WEIGHT_MAX="${POS_WEIGHT_MAX:-12.0}"
INNER_VAL_FILES="${INNER_VAL_FILES:-10}"
PATIENCE="${PATIENCE:-35}"
NUM_WORKERS="${NUM_WORKERS:-0}"
DEVICE="${DEVICE:-auto}"
SEED="${SEED:-2026}"

ARGS=(
  --base-cache-dir "${BASE_CACHE_DIR}"
  --labels-path "${LABELS_PATH}"
  --sample-submission-path "${SAMPLE_SUBMISSION_PATH}"
  --output-dir "${OUTPUT_DIR}"
  --n-folds "${N_FOLDS}"
  --fold-assignment-path "${FOLD_ASSIGNMENT_PATH}"
  --limit-files "${LIMIT_FILES}"
  --mlp-min-pos "${MLP_MIN_POS}"
  --hidden-dims "${HIDDEN_DIMS}"
  --dropout "${DROPOUT}"
  --protoclr-weight-stage1 "${PROTOCLR_WEIGHT_STAGE1}"
  --protoclr-weight-stage2 "${PROTOCLR_WEIGHT_STAGE2}"
  --protoclr-temperature "${PROTOCLR_TEMPERATURE}"
  --protoclr-min-classes "${PROTOCLR_MIN_CLASSES}"
  --protoclr-min-pos-per-class "${PROTOCLR_MIN_POS_PER_CLASS}"
  --stage1-epochs "${STAGE1_EPOCHS}"
  --stage2-epochs "${STAGE2_EPOCHS}"
  --batch-size "${BATCH_SIZE}"
  --lr-stage1 "${LR_STAGE1}"
  --lr-stage2 "${LR_STAGE2}"
  --weight-decay "${WEIGHT_DECAY}"
  --pos-weight-power "${POS_WEIGHT_POWER}"
  --pos-weight-max "${POS_WEIGHT_MAX}"
  --inner-val-files "${INNER_VAL_FILES}"
  --patience "${PATIENCE}"
  --num-workers "${NUM_WORKERS}"
  --device "${DEVICE}"
  --seed "${SEED}"
)

if [[ "${USE_AUDIO_PRETRAIN}" == "1" ]]; then
  ARGS+=(--use-audio-pretrain)
  ARGS+=(--audio-cache-dir "${AUDIO_CACHE_DIR}")
fi

"${PYTHON_BIN}" birdclef2026_perch_embedding_mlp_train.py "${ARGS[@]}"
